# Generated by Django 2.2.1 on 2020-10-28 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=30, verbose_name='名称')),
                ('intro', models.CharField(max_length=300, verbose_name='简介')),
                ('sell', models.PositiveIntegerField(verbose_name='销量')),
                ('image_top', models.CharField(max_length=255, verbose_name='图片')),
                ('brank', models.CharField(max_length=50, verbose_name='品牌')),
                ('unit', models.CharField(max_length=80, verbose_name='单位')),
                ('price', models.PositiveIntegerField(verbose_name='价格')),
                ('state', models.BooleanField(default=True, verbose_name='状态')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
            ],
            options={
                'verbose_name': '商品表',
                'verbose_name_plural': '商品表',
            },
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=30, verbose_name='名称')),
                ('pic_one', models.CharField(max_length=255, verbose_name='图片1')),
                ('pic_two', models.CharField(max_length=255, verbose_name='图片2')),
                ('pic_three', models.CharField(max_length=255, verbose_name='图片3')),
                ('pic_four', models.CharField(max_length=255, verbose_name='图片4')),
            ],
            options={
                'verbose_name': '图片表',
                'verbose_name_plural': '图片表',
            },
        ),
        migrations.CreateModel(
            name='SmallKindModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=30, verbose_name='小种类')),
                ('log', models.CharField(max_length=300, verbose_name='图片')),
            ],
            options={
                'verbose_name': '小种类表',
                'verbose_name_plural': '小种类表',
            },
        ),
        migrations.CreateModel(
            name='SwiperModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('goods_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Sgoods_id', to='wx_api.GoodsModel', verbose_name='商品(外）')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
            },
        ),
        migrations.CreateModel(
            name='RecommendModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('goods_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Rgoods_id', to='wx_api.GoodsModel', verbose_name='商品(外）')),
            ],
            options={
                'verbose_name': '推荐表',
                'verbose_name_plural': '推荐表',
            },
        ),
        migrations.CreateModel(
            name='HeadlineModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=30, verbose_name='标题')),
                ('smallkind_Mang', models.ManyToManyField(related_name='smallkind_Mang', to='wx_api.SmallKindModel', verbose_name='标题表（大多）')),
            ],
            options={
                'verbose_name': '标题表',
                'verbose_name_plural': '标题表',
            },
        ),
        migrations.AddField(
            model_name='goodsmodel',
            name='image_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_id', to='wx_api.ImageModel', verbose_name='图片(外）'),
        ),
        migrations.AddField(
            model_name='goodsmodel',
            name='kind',
            field=models.ManyToManyField(related_name='Gsmall_many', to='wx_api.SmallKindModel', verbose_name='种类'),
        ),
        migrations.CreateModel(
            name='BigKindModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=30, verbose_name='大种类')),
                ('headline_Mang', models.ManyToManyField(related_name='headline_Mang', to='wx_api.HeadlineModel', verbose_name='标题表（大多）')),
            ],
            options={
                'verbose_name': '大种类表',
                'verbose_name_plural': '大种类表',
            },
        ),
    ]
