# Generated by Django 2.2.1 on 2020-11-03 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wx_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='单元楼')),
            ],
            options={
                'verbose_name_plural': '单元楼',
                'verbose_name': '单元楼',
            },
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='住户地址')),
            ],
            options={
                'verbose_name_plural': '住户',
                'verbose_name': '住户',
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='楼层名称')),
                ('resident_key', models.ManyToManyField(to='wx_api.Resident', verbose_name='住户')),
            ],
            options={
                'verbose_name_plural': '楼层名称',
                'verbose_name': '楼层名称',
            },
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='小区名')),
                ('address', models.CharField(max_length=100, verbose_name='地址')),
                ('apartment_key', models.ManyToManyField(to='wx_api.Apartment', verbose_name='单元楼')),
            ],
            options={
                'verbose_name_plural': '小区',
                'verbose_name': '小区',
            },
        ),
        migrations.AddField(
            model_name='apartment',
            name='floor_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wx_api.Floor', verbose_name='楼层'),
        ),
    ]
