# Generated by Django 2.2.1 on 2020-11-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx_api', '0002_auto_20201103_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='floor_key',
        ),
        migrations.AddField(
            model_name='apartment',
            name='floor_key',
            field=models.ManyToManyField(to='wx_api.Floor', verbose_name='楼层'),
        ),
    ]
