# Generated by Django 2.2.1 on 2020-11-07 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx_api', '0003_auto_20201103_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('openid', models.CharField(max_length=100, verbose_name='openid')),
            ],
            options={
                'verbose_name_plural': '用户表',
                'verbose_name': '用户表',
            },
        ),
        migrations.CreateModel(
            name='SHOUHUO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('shouhuo_phone', models.CharField(max_length=11, verbose_name='收货手机号')),
                ('shouhuo_person', models.CharField(max_length=20, verbose_name='收货人')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('address_key', models.ManyToManyField(to='wx_api.Community', verbose_name='地址表')),
            ],
            options={
                'verbose_name_plural': '收货表',
                'verbose_name': '收货表',
            },
        ),
    ]
