# Generated by Django 2.2.1 on 2020-11-12 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wx_api', '0004_shouhuo_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('orderid', models.CharField(max_length=64, verbose_name='订单号')),
                ('num', models.SmallIntegerField(verbose_name='数量')),
                ('total_price', models.SmallIntegerField(verbose_name='单个总价')),
                ('paystatus', models.BooleanField(default=False, verbose_name='支付状态')),
                ('shouhuostatus', models.BooleanField(default=False, verbose_name='收货状态')),
                ('address_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wx_api.SHOUHUO', verbose_name='收货表')),
                ('goods', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wx_api.GoodsModel', verbose_name='商品')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wx_api.UserInfo', verbose_name='用户')),
            ],
            options={
                'verbose_name': '订单表',
                'verbose_name_plural': '订单表',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('description', models.CharField(max_length=300, verbose_name='描述')),
                ('pic_one', models.CharField(max_length=300, verbose_name='图片１')),
                ('pic_two', models.CharField(blank=True, max_length=300, null=True, verbose_name='图片２')),
                ('pic_three', models.CharField(blank=True, max_length=300, null=True, verbose_name='图片３')),
                ('pic_four', models.CharField(blank=True, max_length=300, null=True, verbose_name='图片４')),
                ('pic_five', models.CharField(blank=True, max_length=300, null=True, verbose_name='图片５')),
                ('pic_six', models.CharField(blank=True, max_length=300, null=True, verbose_name='图片６')),
                ('pic_seven', models.CharField(blank=True, max_length=300, null=True, verbose_name='图片７')),
                ('pic_eight', models.CharField(blank=True, max_length=300, null=True, verbose_name='图片８')),
                ('pic_nine', models.CharField(blank=True, max_length=300, null=True, verbose_name='图片９')),
                ('user_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wx_api.UserInfo', verbose_name='用户')),
            ],
            options={
                'verbose_name': '意见表',
                'verbose_name_plural': '意见表',
            },
        ),
    ]
