# Generated by Django 2.2.1 on 2020-11-16 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx_api', '0005_feedback_ordermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='backpaystatus',
            field=models.BooleanField(default=False, verbose_name='退货'),
        ),
    ]
